### ISSUE TITLE
Plato web based set-up v1.1.1 Db Error

### ISSUE THREAD

**Issue by sabrikrdnz** [InstantASP/Plato#33]
Hi,

After i deploy Plato to IIS, it worked well then i started to configure database step.
This is my connection string;

**server=my_sqlserver_ip;uid=username;pwd=password;database=Plato**

But it throws errors which i sent you below. Do you have any idea?

- at PlatoCore.Data.Providers.SqlProvider.HandleException(Exception ex) in C:\Git\Plato\src\Core\Data\Providers\SqlProvider.cs:line 294 at PlatoCore.Data.Providers.SqlProvider.ExecuteReaderAsync[T](CommandType commandType, String commandText, Func'2 populate, IDbDataParameter[] dbParams) in C:\Git\Plato\src\Core\Data\Providers\SqlProvider.cs:line 72 at PlatoCore.Data.DbContext.ExecuteReaderAsync[T](CommandType commandType, String commandText, Func'2 populate, IDbDataParameter[] dbParams) in C:\Git\Plato\src\Core\Data\DbContext.cs:line 44 at PlatoCore.Repositories.Abstract.DictionaryRepository.SelectEntries() in C:\Git\Plato\src\Core\Repositories\Abstract\DictionaryRepository.cs:line 101 at PlatoCore.Stores.Abstract.DictionaryStore.GetAllKeys() in C:\Git\Plato\src\Core\Stores\Abstract\DictionaryStore.cs:line 92 at PlatoCore.Stores.Abstract.DictionaryStore.GetByKeyAsync(String key) in C:\Git\Plato\src\Core\Stores\Abstract\DictionaryStore.cs:line 85 at PlatoCore.Stores.Abstract.DictionaryStore.UpdateAsync[T](String key, ISerializable value) in C:\Git\Plato\src\Core\Stores\Abstract\DictionaryStore.cs:line 54 at PlatoCore.Stores.Settings.SiteSettingsStore.SaveAsync(ISiteSettings siteSettings) in C:\Git\Plato\src\Core\Stores\Settings\SiteSettingsStore.cs:line 60 at Plato.Settings.Handlers.SetUpEventHandler.SetUp(SetUpContext context, Action'2 reportError) in C:\Git\Plato\src\Web\Modules\Plato.Settings\Handlers\SetUpEventHandler.cs:line 46

- SetUp within Plato.Users.Handlers.SetUpEventHandler - Must declare the scalar variable "@id".

- at PlatoCore.Data.Providers.SqlProvider.HandleException(Exception ex) in C:\Git\Plato\src\Core\Data\Providers\SqlProvider.cs:line 294 at PlatoCore.Data.Providers.SqlProvider.ExecuteReaderAsync[T](CommandType commandType, String commandText, Func'2 populate, IDbDataParameter[] dbParams) in C:\Git\Plato\src\Core\Data\Providers\SqlProvider.cs:line 72 at PlatoCore.Data.DbContext.ExecuteReaderAsync[T](CommandType commandType, String commandText, Func'2 populate, IDbDataParameter[] dbParams) in C:\Git\Plato\src\Core\Data\DbContext.cs:line 44 at PlatoCore.Repositories.Users.UserRepository.SelectByUserNameNormalizedAsync(String userNameNormalized) in C:\Git\Plato\src\Core\Repositories\Users\UserRepository.cs:line 69 at PlatoCore.Stores.Users.PlatoUserStore.<>c__DisplayClass24_0.<<GetByUserNameNormalizedAsync>b__0>d.MoveNext() in C:\Git\Plato\src\Core\Stores\Users\PlatoUserStore.cs:line 207 --- End of stack trace from previous location where exception was thrown --- at PlatoCore.Cache.SimpleCacheManager.GetOrCreateAsync[TItem](CacheToken token, Func'2 factory) in C:\Git\Plato\src\Core\Cache\SimpleCacheManager.cs:line 76 at PlatoCore.Stores.Users.PlatoUserStore.GetByUserNameNormalizedAsync(String userNameNormalized) in C:\Git\Plato\src\Core\Stores\Users\PlatoUserStore.cs:line 205 at PlatoCore.Stores.Users.UserStore.FindByNameAsync(String normalizedUserName, CancellationToken cancellationToken) in C:\Git\Plato\src\Core\Stores\Users\UserStore.cs:line 130 at Microsoft.AspNetCore.Identity.UserManager'1.FindByNameAsync(String userName) at Microsoft.AspNetCore.Identity.UserValidator'1.ValidateUserName(UserManager'1 manager, TUser user, ICollection'1 errors) at Microsoft.AspNetCore.Identity.UserValidator'1.ValidateAsync(UserManager'1 manager, TUser user) at Microsoft.AspNetCore.Identity.UserManager'1.ValidateUserAsync(TUser user) at Microsoft.AspNetCore.Identity.UserManager'1.CreateAsync(TUser user) at Microsoft.AspNetCore.Identity.UserManager'1.CreateAsync(TUser user, String password) at Plato.Users.Handlers.SetUpEventHandler.ConfigureDefaultUsers(SetUpContext context, Action'2 reportError) in C:\Git\Plato\src\Web\Modules\Plato.Users\Handlers\SetUpEventHandler.cs:line 402

- SetUp within Plato.Core.Handlers.SetUpEventHandler - There is already an object named 'plato_DocumentEntries' in the database.

- SetUp within Plato.Core.Handlers.SetUpEventHandler - There is already an object named 'plato_DictionaryEntries' in the database.

Thanks,
Sabri

**Comment by InstantASP** [comment]
Hi @sabrikrdnz,

Apologies for my delay. I've been head down over the last few days getting Plato 2.0.0 ready for release. This will be available tomorrow :)

I'm sorry to hear of the issues you've encountered. 

Your database connection string looks correct. 

First if your able to login can you check to see if any updates are available or failing. You would need to visit the Dashboard, click Features on the left and then click Manage. Search for "Update". Enable the Plato Features Updates feature. 

Once Plato.Features.Updates is enabled you should see a new "Updates" link under the "Features" link within the dashboard. If you click this "Updates" link you should see a list of any updates that could not be automatically applied due to errors that may have occrred. Are you able to apply the update manually using the "Update" button if you see any out of date featyres? 

I wonder if this could be a collation issue. 

If you execute the SQL code below against your Plato database what result do you see?

```
--Verify the collation setting.  
SELECT name, collation_name  
FROM sys.databases  
WHERE name = N'plato';  
GO  
```

If you see something like Latin1_General_CS_AS this could indicate your SQL Server database is case-sensitive which may cause problems. 

If you see Latin1_General_CI_AS then this means your database is case-insensitive and the issues may be caused by smething else. 

Do you see "CS" within the result when running the above query? We have not fully tested Plato against case-sentive databases yet which is why I'm suggesting this could be the cause. 

Please let me know what result you see or if anything has changed and I'll certainly assist further more promptly. Of course thank you for trying Plato I'm sorry you had to encounter these issues. 

P.S. If your able to upgrade to the very latest 2.0.0 code tomorrow this resolves a number of important issues around set-up as we've introduced true multi-tenancy support in this update. 

I look forward to hearing from you and assisting further,

**Comment by sabrikrdnz** [comment]
Hi,

I'm not able to login even i can not go through from first screen. 

`--Verify the collation setting.  
SELECT name, collation_name  
FROM sys.databases  
WHERE name = N'plato';  
GO  `

> RESULT
> Plato	Turkish_CI_AS

I tried to publish 2.0 version and still throwing this issue. Also when i click Finish Setup button and after get i some errors, when i try again it says admin user already exist, is there any control if a user exist just pass them? 

Thanks for helping,
Sabri

**Comment by arham-anees** [comment]
hi, I am facing a problem that i executed application once but i was unable to login with provided email and password on setup page. 
as the password stores is hashed, i tried to execute it from start again so i deleted the database from server. now when i run application it throws nullPointerException which is obvious due to missing database. 
I tried ef core but that is not used here so how can i reset everything and create my database again?
